---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check that the filebeat.yml exists
      stat:
        path: /etc/filebeat/filebeat.yml
      register: stat_result
      failed_when: not stat_result.stat.exists

    - name: Check if filebeat is running
      command: systemctl status filebeat
      ignore_errors: yes
      changed_when: false
      register: service_filebeat_status

    - name: Report status of filebeat
      fail:
        msg: |
          Service filebeat is not running.
          Output of `systemctl status filebeat`:
          {{ service_filebeat_status.stdout }}
          {{ service_filebeat_status.stderr }}
      when: service_filebeat_status | failed